[project]
name = 'shiny_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.storage_expiration]
path = 'contracts/storage_expiration.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_identy]
path = 'contracts/user_identy.clar'
clarity_version = 2
epoch = 2.5

[contracts.voter_whitelist_and_blacklist]
path = 'contracts/voter_whitelist_and_blacklist.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
